# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7fdbd8dfde9f743a701269befc49bad2afefb268addeb649c11e1b2496e4df166f9a461f01475fe08f502e2c9a4c8e384e88f57706bc375fbef7f6f4b6bbb0f
  twitter_api_key: IcrGHWnaFdj1qlyQZird17y0y
  twitter_api_secret: hRfBxe0AwQWeaYnC1iDWGGdRb0NsZxIL5ILl5qcXowhAQiaBEG
  facebook_api_key: 1433427763637451
  facebook_api_secret: 6b859dcd5b96e587d4cf0b4e99caece6
test:
  secret_key_base: d49f8e770207dbec7e6edd9ef0fb1ecb4daaeed2897d3f25144368e6dcb52157e65e2966047297367a1113ad39bbae7afe5033be46333f508dc8a0af1e52c053

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: IcrGHWnaFdj1qlyQZird17y0y
  twitter_api_secret: hRfBxe0AwQWeaYnC1iDWGGdRb0NsZxIL5ILl5qcXowhAQiaBEG
  facebook_api_key: 1433427763637451
  facebook_api_secret: 6b859dcd5b96e587d4cf0b4e99caece6
